<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MasterPendudukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('master_penduduks')->insert([
            // KK 1: 3175091501230022
            [
                'nik' => '3508160711800001',
                'nama_lengkap' => 'Budi Santoso',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Lumajang',
                'tanggal_lahir' => '1980-11-07',
                'agama' => 'Islam',
                'pendidikan' => 'S1',
                'pekerjaan' => 'PNS',
                'golongan_darah' => 'O',
                'status_perkawinan' => 'Menikah',
                'tanggal_perkawinan' => '2005-05-10',
                'status_keluarga' => 'Kepala Keluarga',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null, 'no_kitap' => null,
                'nama_ayah' => 'Supardi', 'nama_ibu' => 'Sumiati',
                'no_kk' => '3175091501230022',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'nik' => '3508164711850002',
                'nama_lengkap' => 'Siti Aminah',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1985-05-12',
                'agama' => 'Islam',
                'pendidikan' => 'SMA',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'golongan_darah' => 'A',
                'status_perkawinan' => 'Menikah',
                'tanggal_perkawinan' => '2005-05-10',
                'status_keluarga' => 'Istri',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null, 'no_kitap' => null,
                'nama_ayah' => 'Hasan', 'nama_ibu' => 'Fatima',
                'no_kk' => '3175091501230022',
                'created_at' => now(), 'updated_at' => now(),
            ],

            // KK 2: 3175091501230032
            [
                'nik' => '3508161503900001',
                'nama_lengkap' => 'Agus Setiawan',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '1990-03-15',
                'agama' => 'Islam',
                'pendidikan' => 'D3',
                'pekerjaan' => 'Wiraswasta',
                'golongan_darah' => 'B',
                'status_perkawinan' => 'Menikah',
                'tanggal_perkawinan' => '2016-08-20',
                'status_keluarga' => 'Kepala Keluarga',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null, 'no_kitap' => null,
                'nama_ayah' => 'Toni', 'nama_ibu' => 'Ratna',
                'no_kk' => '3175091501230032',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'nik' => '3508165503920002',
                'nama_lengkap' => 'Rina Wijaya',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Lumajang',
                'tanggal_lahir' => '1992-04-10',
                'agama' => 'Islam',
                'pendidikan' => 'SMA',
                'pekerjaan' => 'Karyawan Swasta',
                'golongan_darah' => 'O',
                'status_perkawinan' => 'Menikah',
                'tanggal_perkawinan' => '2016-08-20',
                'status_keluarga' => 'Istri',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null, 'no_kitap' => null,
                'nama_ayah' => 'Bambang', 'nama_ibu' => 'Siska',
                'no_kk' => '3175091501230032',
                'created_at' => now(), 'updated_at' => now(),
            ],

            // KK 3: 3175091501230042
            [
                'nik' => '3508162002880001',
                'nama_lengkap' => 'Hendra Pratama',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1988-02-20',
                'agama' => 'Kristen',
                'pendidikan' => 'S1',
                'pekerjaan' => 'Arsitek',
                'golongan_darah' => 'AB',
                'status_perkawinan' => 'Menikah',
                'tanggal_perkawinan' => '2014-12-12',
                'status_keluarga' => 'Kepala Keluarga',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => 'B123456', 'no_kitap' => null,
                'nama_ayah' => 'Robert', 'nama_ibu' => 'Elisabeth',
                'no_kk' => '3175091501230042',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'nik' => '3508161010150002',
                'nama_lengkap' => 'Kevin Pratama',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Lumajang',
                'tanggal_lahir' => '2015-10-10',
                'agama' => 'Kristen',
                'pendidikan' => 'SD',
                'pekerjaan' => 'Pelajar',
                'golongan_darah' => 'A',
                'status_perkawinan' => 'Belum Menikah',
                'tanggal_perkawinan' => null,
                'status_keluarga' => 'Anak',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null, 'no_kitap' => null,
                'nama_ayah' => 'Hendra Pratama', 'nama_ibu' => 'Maria Indah',
                'no_kk' => '3175091501230042',
                'created_at' => now(), 'updated_at' => now(),
            ],

            // KK 4: 3175091501230052
            [
                'nik' => '3508160505750001',
                'nama_lengkap' => 'Mulyono',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Solo',
                'tanggal_lahir' => '1975-05-05',
                'agama' => 'Islam',
                'pendidikan' => 'SMP',
                'pekerjaan' => 'Petani',
                'golongan_darah' => 'O',
                'status_perkawinan' => 'Menikah',
                'tanggal_perkawinan' => '1998-02-02',
                'status_keluarga' => 'Kepala Keluarga',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null, 'no_kitap' => null,
                'nama_ayah' => 'Kromo', 'nama_ibu' => 'Poniyem',
                'no_kk' => '3175091501230052',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'nik' => '3508164505800002',
                'nama_lengkap' => 'Sri Wahyuni',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Lumajang',
                'tanggal_lahir' => '1980-05-05',
                'agama' => 'Islam',
                'pendidikan' => 'SMP',
                'pekerjaan' => 'Petani',
                'golongan_darah' => 'B',
                'status_perkawinan' => 'Menikah',
                'tanggal_perkawinan' => '1998-02-02',
                'status_keluarga' => 'Istri',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null, 'no_kitap' => null,
                'nama_ayah' => 'Yanto', 'nama_ibu' => 'Sumi',
                'no_kk' => '3175091501230052',
                'created_at' => now(), 'updated_at' => now(),
            ],

            // KK 5: 3175091501230062
            [
                'nik' => '3508161212950001',
                'nama_lengkap' => 'Fajar Ramadhan',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '1995-12-12',
                'agama' => 'Islam',
                'pendidikan' => 'S1',
                'pekerjaan' => 'Programmer',
                'golongan_darah' => 'O',
                'status_perkawinan' => 'Belum Menikah',
                'tanggal_perkawinan' => null,
                'status_keluarga' => 'Kepala Keluarga',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null, 'no_kitap' => null,
                'nama_ayah' => 'Ali', 'nama_ibu' => 'Fatimah',
                'no_kk' => '3175091501230062',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'nik' => '3508161212980002',
                'nama_lengkap' => 'Adit Pratama',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '1998-06-12',
                'agama' => 'Islam',
                'pendidikan' => 'SMA',
                'pekerjaan' => 'Mahasiswa',
                'golongan_darah' => 'A',
                'status_perkawinan' => 'Belum Menikah',
                'tanggal_perkawinan' => null,
                'status_keluarga' => 'Adik',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null, 'no_kitap' => null,
                'nama_ayah' => 'Ali', 'nama_ibu' => 'Fatimah',
                'no_kk' => '3175091501230062',
                'created_at' => now(), 'updated_at' => now(),
            ],
        ]);
    }
}
