services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: laravel_app
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - app_storage:/var/www/html/storage
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - laravel_net

  mysql:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: semester6
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - laravel_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: unless-stopped
    networks:
      - laravel_net

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9101:9100"
    restart: unless-stopped
    networks:
      - laravel_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - laravel_net

volumes:
  app_storage:
  db_data:
  prometheus_data:
  grafana_data:

networks:
  laravel_net: