name: Deploy Laravel Docker to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}

            echo "Fix project permission..."
            chown -R root:root ${{ secrets.PROJECT_PATH }}
            chmod -R u+rwX ${{ secrets.PROJECT_PATH }}

            echo "Remove git lock files..."
            rm -f ${{ secrets.PROJECT_PATH }}/.git/FETCH_HEAD
            rm -f ${{ secrets.PROJECT_PATH }}/.git/index.lock

            echo "Set safe directory..."
            git config --global --add safe.directory ${{ secrets.PROJECT_PATH }}

            echo "Run deploy script..."
            bash deploy.sh